//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicación_Hoteles.MetodosWeb_Hoteles {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetodosWeb_Hoteles.MetodosWeb_HotelesSoap")]
    public interface MetodosWeb_HotelesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllFromHoteles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllFromHoteles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllFromHoteles", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllFromHotelesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MetodosWeb_HotelesSoapChannel : Aplicación_Hoteles.MetodosWeb_Hoteles.MetodosWeb_HotelesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetodosWeb_HotelesSoapClient : System.ServiceModel.ClientBase<Aplicación_Hoteles.MetodosWeb_Hoteles.MetodosWeb_HotelesSoap>, Aplicación_Hoteles.MetodosWeb_Hoteles.MetodosWeb_HotelesSoap {
        
        public MetodosWeb_HotelesSoapClient() {
        }
        
        public MetodosWeb_HotelesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetodosWeb_HotelesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosWeb_HotelesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosWeb_HotelesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllFromHoteles() {
            return base.Channel.GetAllFromHoteles();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllFromHotelesAsync() {
            return base.Channel.GetAllFromHotelesAsync();
        }
    }
}
